# Generated by cpp11: do not edit by hand

compress <- function(x) {
  .Call(`_tinyint_compress`, x)
}

get <- function(ptr, pos) {
  .Call(`_tinyint_get`, ptr, pos)
}

gets <- function(ptr, pos) {
  .Call(`_tinyint_gets`, ptr, pos)
}
