# Generated by cpp11: do not edit by hand

tinyint_compress_ <- function(x) {
  .Call(`_tinyint_tinyint_compress_`, x)
}

tinyint_get_ <- function(ptr, pos) {
  .Call(`_tinyint_tinyint_get_`, ptr, pos)
}

tinyint_gets_ <- function(ptr, pos) {
  .Call(`_tinyint_tinyint_gets_`, ptr, pos)
}

tinyint_size_ <- function(ptr) {
  .Call(`_tinyint_tinyint_size_`, ptr)
}

tinyint_index_ <- function(ptr, x) {
  .Call(`_tinyint_tinyint_index_`, ptr, x)
}

tinyint_contains_ <- function(ptr, x) {
  .Call(`_tinyint_tinyint_contains_`, ptr, x)
}
